create user usnower@'localhost' identified by 'usnower';
create database usnower default charset utf8;
grant all on usnower.* to usnower;


/*------------------------------------------------
USNOWER_ADMIN
------------------------------------------------*/
CREATE TABLE USNOWER_ADMIN (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ADMIN VARCHAR(30) NOT NULL UNIQUE KEY,
	PWD VARCHAR(32) NOT NULL COMMENT 'MD5',
	IN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	LAST_TIME TIMESTAMP,
	LAST_IP INT COMMENT 'INET_ATON'
);

DELIMITER //
CREATE TRIGGER USNOWER_ADMIN_I BEFORE INSERT ON USNOWER_ADMIN FOR EACH ROW
BEGIN
	SET NEW.PWD = MD5(NEW.PWD);
END//

////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TRIGGER USNOWER_ADMIN_U BEFORE UPDATE ON USNOWER_ADMIN FOR EACH ROW
BEGIN
	IF(NEW.PWD != OLD.PWD) THEN
	SET NEW.PWD = MD5(NEW.PWD);
	END IF;
END//

CREATE FUNCTION USNOWER_F_ISADMIN(IN_ADMIN VARCHAR(30),IN_PWD VARCHAR(32)) RETURNS BOOL
BEGIN
	DECLARE N BOOL;
	SELECT COUNT(1) INTO N FROM USNOWER_ADMIN WHERE ADMIN = IN_ADMIN AND PWD = MD5(IN_PWD);
	RETURN N;
END//

CREATE PROCEDURE USNOWER_P_ADMIN_LOGIN(IN IN_ADMIN VARCHAR(30),IN IN_IP VARCHAR(15))
BEGIN
	UPDATE USNOWER_ADMIN SET LAST_TIME = CURRENT_TIMESTAMP(),LAST_IP = INET_ATON(IN_IP) WHERE ADMIN = IN_ADMIN;
END//
DELIMITER ;


/*-----------------------------------------------------
USNOWER_UTRACK
*/-----------------------------------------------------
CREATE TABLE USNOWER_UTRACK(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REQUIRE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),	

	IP INT NOT NULL COMMENT 'INET_ATON',
	OS VARCHAR(10),
	LANG VARCHAR(10),
	BROWSER VARCHAR(10),
	BROWSER_VERSION VARCHAR(10),
	FLASH_VERSION VARCHAR(10),
	COOKIE_ENABLED BOOL,
	JAVA_ENABLED BOOL,
	
	URL VARCHAR(300) COMMENT 'location.href',
	REFERRER VARCHAR(300) COMMENT 'document.referrer',

	CLIENT_ID VARCHAR(30) COMMENT 'FROM COOKIE'
)


/*-------------------------------------------------------------
USNOWER_ART_CAT 文章分类


CREATE TABLE USNOWER_ART_TYPE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	FA_ID INT NOT NULL DEFAULT -1 COMMENT 'FATHER ID,IF -1 THEN NO FATHER',
	IN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT UNIQUE KEY USNOWER_UNI_ART_TYPE_NAME (FA_ID,NAME)
);

--------------------------------------------------------------*/
CREATE TABLE USNOWER_ART_CAT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(30) NOT NULL,
  FA_ID int NOT NULL DEFAULT -1 COMMENT 'FATHER ID,IF -1 THEN NO FATHER',
  IN_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`FA_ID`,`NAME`)
);
